import { DS } from './design-tokens';

export { DS } from './design-tokens';

// Backwards-compatible aliases. New and migrated screens consume DS directly.
export const C = {
  bg: DS.color.canvas,
  bgSplash: DS.color.splash,
  bgGradient: DS.gradient.home,
  bgGradientStart: DS.gradient.start,
  bgGradientEnd: DS.gradient.end,
  pink: DS.color.brandPrimary,
  pinkDeep: DS.color.brandStrong,
  pinkLight: DS.color.brandSubtle,
  pinkBorder: DS.color.brandBorder,
  pinkMid: DS.color.brandSelected,
  text: DS.color.textPrimary,
  refineCandidateStrong: DS.color.refineCandidate.contentStrong,
  textSub: DS.color.textSecondary,
  locationMuted: DS.color.textLocation,
  textMuted: DS.color.textMuted,
  textLight: DS.color.textDisabled,
  textFaint: DS.color.textPlaceholder,
  border: DS.color.borderDefault,
  borderLight: DS.color.borderSubtle,
  white: DS.color.surface,
  canvasWhiteException: DS.color.canvasWhiteException,
  cardBg: DS.color.surface,
  lavender: DS.color.lavenderSurface,
  lavenderFg: DS.color.lavenderForeground,
  mint: DS.color.mintSurface,
  mintFg: DS.color.mintForeground,
  cream: DS.color.creamSurface,
  creamFg: DS.color.creamForeground,
  creamBorder: DS.color.borderCream,
  closeSurface: DS.color.closeSurface,
  reviewBorder: DS.color.reviewBorder,
  reviewDivider: DS.color.reviewDivider,
  onboardingCheckBorder: DS.color.onboardingCheckBorder,
  anniversaryBorder: DS.color.anniversaryBorder,
  avatarBorder: DS.color.avatarBorder,
  gray: DS.color.graySurface,
  grayFg: DS.color.grayForeground,
  dark: DS.color.darkSurface,
  danger: DS.color.danger,
  shadow: DS.color.shadowWarm,
  ink: DS.color.ink,
  inkSoft: DS.color.inkSoft,
  coolGray: DS.color.coolGray,
  coolGrayLight: DS.color.coolGrayLight,
  disabledBg: DS.color.surfaceDisabled,
  catMeal: DS.color.categoryMeal,
  catCafe: DS.color.categoryCafe,
  catWalk: DS.color.categoryWalk,
  googleBorder: DS.color.socialGoogleBorder,
  googleText: DS.color.socialGoogleText,
  googleRed: DS.color.socialGoogleRed,
  googleBlue: DS.color.socialGoogleBlue,
  googleYellow: DS.color.socialGoogleYellow,
  googleGreen: DS.color.socialGoogleGreen,
} as const;
