/**
 * Product design tokens, derived from the shipped Loading and Quick Planning
 * Input surfaces. Screens consume compatibility aliases from `theme.ts` until
 * they are migrated to this semantic contract.
 */
export const DS = {
  color: {
    canvas: '#FFF9FC',
    canvasWhiteException: '#FFFFFF',
    splash: '#FFF1F6',
    surface: '#FFFFFF',
    surfaceDisabled: '#EFE7DF',
    brandPrimary: '#F26B7A',
    brandStrong: '#C24B57',
    brandSubtle: '#FFEEF0',
    brandBorder: '#F2A8B0',
    brandSelected: '#FFD3D9',
    textPrimary: '#3B2E2E',
    darkSurface: '#1F1F24',
    overlayScrim: 'rgba(31, 31, 36, 0.28)',
    avatarOverlay: 'rgba(40, 30, 25, 0.4)',
    tabBorder: '#EFE5DA',
    tabSurface: 'rgba(255, 255, 255, 0.97)',
    surfaceOverlay: 'rgba(255, 255, 255, 0.8)',
    textSecondary: '#8A7F76',
    textLocation: '#8A8075',
    textMuted: '#A89B92',
    textDisabled: '#B8AEA6',
    textPlaceholder: '#C8BCB1',
    borderDefault: '#F2E0DC',
    borderSubtle: '#F2E7DC',
    borderCream: '#F4E2CE',
    reviewBorder: '#F2BDC2',
    reviewDivider: '#F5E5E8',
    onboardingCheckBorder: '#E0D5CB',
    anniversaryBorder: '#F2DDB0',
    avatarBorder: '#F2D6DA',
    shadowWarm: '#785046',
    creamSurface: '#FFF3E0',
    creamForeground: '#A77738',
    closeSurface: '#E5E7EB',
    graySurface: '#F2EBE3',
    grayForeground: '#6B5247',
    lavenderSurface: '#F1ECFF',
    lavenderForeground: '#6B5BB8',
    lavenderSelected: '#D7CAFF',
    mintSurface: '#E3F2EA',
    mintForeground: '#3E8C5F',
    mintSelected: '#B7DDC6',
    creamSelected: '#FFDDB0',
    graySelected: '#DDD2C5',
    blueSurface: '#E8F1FC',
    danger: '#FF4F6D',
    ink: '#1A1A1A',
    inkSoft: '#4A4A55',
    coolGray: '#6B7280',
    coolGrayLight: '#9CA3AF',
    categoryMeal: '#FD8956',
    categoryCafe: '#6B9FDB',
    categoryWalk: '#5DBD5F',
    socialGoogleBorder: '#747775',
    socialGoogleText: '#1F1F1F',
    socialGoogleRed: '#EA4335',
    socialGoogleBlue: '#4285F4',
    socialGoogleYellow: '#FBBC05',
    socialGoogleGreen: '#34A853',
    refineCandidate: {
      contentStrong: '#3B2E2E',
    },
    selection: {
      like: {
        background: '#FFF3E0',
        border: '#A77738',
        foreground: '#A77738',
        borderWidth: 2,
      },
    },
  },
  gradient: {
    home: ['#FFF1F6', '#FFFFFF'] as const,
    splash: ['#FFF1F6', '#FFFFFF'] as const,
    start: { x: 0, y: 0 } as const,
    end: { x: 1, y: 1 } as const,
  },
  spacing: {
    micro: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    screen: 20,
    xl: 20,
    xxl: 24,
    section: 32,
    xxxl: 32,
    hero: 40,
    art: 48,
    splash: 56,
    tab: 64,
    touch: 44,
    input: 52,
    multilineInput: 112,
  },
  radius: {
    badge: 6,
    compact: 12,
    small: 10,
    legacyInput: 14,
    input: 16,
    button: 18,
    chip: 20,
    card: 22,
    modal: 24,
    full: 999,
  },
  typography: {
    display: { fontSize: 30, lineHeight: 36, fontWeight: '800' },
    inputTitle: { fontSize: 26, lineHeight: 34, fontWeight: '700' },
    authTitle: { fontSize: 26, lineHeight: 34, fontWeight: '800' },
    heroGreeting: { fontSize: 26, lineHeight: 34, fontWeight: '700' },
    heading: { fontSize: 22, lineHeight: 30, fontWeight: '700' },
    headingLegacy: { fontSize: 22, lineHeight: 30, fontWeight: '700' },
    sectionTitle: { fontSize: 19, lineHeight: 26, fontWeight: '700' },
    cardTitle: { fontSize: 15, lineHeight: 20, fontWeight: '700' },
    bodyLarge: { fontSize: 16, lineHeight: 24, fontWeight: '600' },
    body: { fontSize: 14, lineHeight: 22, fontWeight: '500' },
    bodyCompact: { fontSize: 13, lineHeight: 20, fontWeight: '500' },
    bodySmall: { fontSize: 12, lineHeight: 18, fontWeight: '500' },
    label: { fontSize: 13, lineHeight: 20, fontWeight: '600' },
    caption: { fontSize: 11, lineHeight: 16, fontWeight: '500' },
    micro: { fontSize: 10, lineHeight: 14, fontWeight: '500' },
    badge: { fontSize: 10, lineHeight: 12, fontWeight: '600', letterSpacing: 0.2 },
    screenTitle: { fontSize: 24, lineHeight: 32, fontWeight: '800' },
    metric: { fontSize: 20, lineHeight: 24, fontWeight: '800' },
    avatarInitial: { fontSize: 46, lineHeight: 52, fontWeight: '700' },
    inviteCode: { fontSize: 34, lineHeight: 40, fontWeight: '800', letterSpacing: 4 },
    codeInput: { fontSize: 18, lineHeight: 24, fontWeight: '700', letterSpacing: 3 },
    button: { fontSize: 15, lineHeight: 20, fontWeight: '600' },
    buttonCompact: { fontSize: 13, lineHeight: 18, fontWeight: '600' },
  },
  elevation: {
    // Cards are intentionally flat in the approved product system.
    card: {},
    raised: {},
    popover: {
      shadowColor: '#785046', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 16, elevation: 6,
    },
    avatarAction: {
      shadowColor: '#785046', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 3,
    },
    sliderThumb: {
      shadowColor: '#785046', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 3, elevation: 2,
    },
    coursePin: {
      shadowColor: '#785046', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 5, elevation: 3,
    },
    courseBadge: {
      shadowColor: '#785046', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.15, shadowRadius: 2, elevation: 2,
    },
  },
  motion: {
    press: 120,
    content: 200,
    stage: 360,
    progress: 400,
  },
  layout: {
    headerTopInset: 20,
    pageInset: 20,
    headerTitleOffset: 16,
    titleAccessoryGap: 4,
    headerActionGap: 8,
    headerActionGroupGap: 16,
  },
  exception: {
    quickPlanningLoading: {
      compositionTop: 72,
      compositionBottom: 32,
      subtitleTop: 6,
      mascotTop: 7,
      bubbleTop: 8,
      bubblePaddingHorizontal: 10,
      progressTop: 24,
      conditionsTop: 24,
      conditionsGap: 8,
      conditionMetaGap: 16,
      conditionGroupGap: 4,
      statusTop: 24,
      statusHeight: 20,
    },
  },
  component: {
    tightGap: 6,
    splashDotSize: 6,
    badgePaddingVertical: 2,
    stepCardPaddingVertical: 14,
    updateTitleBottom: 14,
    sortRowTop: 10,
    titleInputPaddingVertical: 13,
    chipPaddingVertical: 6,
    chipPaddingHorizontal: 12,
    emptyStateTop: 60,
    bottomOverlaySpacer: 100,
    courseChoiceHeight: 78,
    compactControlHeight: 34,
    timeChipHeight: 30,
    optionCardMinWidth: 76,
    sheetHandleWidth: 36,
    sheetHandleHeight: 4,
    sectionLabelLetterSpacing: 1,
    inviteLabelLetterSpacing: 0.4,
    featuredCategoryLetterSpacing: 0.5,
    appNameLetterSpacing: -0.6,
    iconOpticalOffset: 1,
    stepNumberWidth: 16,
    stepContentOffset: 34,
    ratingGap: 2,
    pickerSelectedLineHeight: 28,
  },
} as const;
