-- 사용자별 코스 생성 AI 보호막. 모든 RPC는 Edge service_role만 호출한다.
begin;

create table if not exists public.ai_quota_buckets (
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action = 'course_generate'),
  bucket_type text not null check (bucket_type in ('burst', 'daily')),
  bucket_start timestamptz not null,
  used_count integer not null default 0 check (used_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, action, bucket_type, bucket_start)
);

create table if not exists public.ai_request_locks (
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action = 'course_generate'),
  request_id text not null check (char_length(btrim(request_id)) between 1 and 120),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  primary key (user_id, action)
);

create table if not exists public.ai_rate_limit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action = 'course_generate'),
  event_type text not null check (event_type in ('lock_conflict', 'burst_rejected', 'daily_rejected')),
  created_at timestamptz not null default now()
);

create index if not exists ai_rate_limit_events_action_created_idx
  on public.ai_rate_limit_events(action, created_at desc);

alter table public.ai_quota_buckets enable row level security;
alter table public.ai_request_locks enable row level security;
alter table public.ai_rate_limit_events enable row level security;
revoke all on public.ai_quota_buckets from public;
revoke all on public.ai_request_locks from public;
revoke all on public.ai_rate_limit_events from public;
revoke all on public.ai_quota_buckets from anon, authenticated;
revoke all on public.ai_request_locks from anon, authenticated;
revoke all on public.ai_rate_limit_events from anon, authenticated;

create or replace function public.acquire_ai_request_lock(
  p_user_id uuid, p_action text, p_request_id text, p_now timestamptz default now()
)
returns table (acquired boolean, retry_after_seconds integer)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_expires_at timestamptz;
begin
  if p_action <> 'course_generate' or nullif(btrim(p_request_id), '') is null then
    raise invalid_parameter_value using message = 'invalid_ai_lock';
  end if;

  insert into public.ai_request_locks(user_id, action, request_id, expires_at)
  values (p_user_id, p_action, p_request_id, p_now + interval '2 minutes')
  on conflict (user_id, action) do update set
    request_id = excluded.request_id,
    expires_at = excluded.expires_at,
    created_at = p_now
  where public.ai_request_locks.expires_at <= p_now
  returning true, 0 into acquired, retry_after_seconds;

  if found then return next; return; end if;

  select expires_at into v_expires_at
  from public.ai_request_locks
  where user_id = p_user_id and action = p_action;
  acquired := false;
  retry_after_seconds := greatest(1, ceil(extract(epoch from (v_expires_at - p_now)))::integer);
  return next;
end;
$$;

create or replace function public.release_ai_request_lock(
  p_user_id uuid, p_action text, p_request_id text
)
returns void language sql security definer set search_path = public, pg_temp as $$
  delete from public.ai_request_locks
  where user_id = p_user_id and action = p_action and request_id = p_request_id;
$$;

create or replace function public.consume_ai_quota(
  p_user_id uuid, p_action text, p_now timestamptz default now()
)
returns table (
  allowed boolean,
  limit_type text,
  retry_after_seconds integer,
  resets_at timestamptz
)
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_burst_limit constant integer := 3;
  v_daily_limit constant integer := 20;
  v_burst_start timestamptz := to_timestamp(floor(extract(epoch from p_now) / 300) * 300);
  v_daily_start timestamptz := ((p_now at time zone 'Asia/Seoul')::date::timestamp at time zone 'Asia/Seoul');
  v_burst_count integer := 0;
  v_daily_count integer := 0;
begin
  if p_action <> 'course_generate' then
    raise invalid_parameter_value using message = 'invalid_ai_action';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_action, 0));

  select used_count into v_burst_count from public.ai_quota_buckets
  where user_id = p_user_id and action = p_action and bucket_type = 'burst' and bucket_start = v_burst_start;
  select used_count into v_daily_count from public.ai_quota_buckets
  where user_id = p_user_id and action = p_action and bucket_type = 'daily' and bucket_start = v_daily_start;
  v_burst_count := coalesce(v_burst_count, 0);
  v_daily_count := coalesce(v_daily_count, 0);

  if v_burst_count >= v_burst_limit then
    return query select false, 'burst', greatest(1, ceil(extract(epoch from ((v_burst_start + interval '5 minutes') - p_now)))::integer), null::timestamptz;
    return;
  end if;
  if v_daily_count >= v_daily_limit then
    return query select false, 'daily', null::integer, v_daily_start + interval '1 day';
    return;
  end if;

  insert into public.ai_quota_buckets(user_id, action, bucket_type, bucket_start, used_count, updated_at)
  values
    (p_user_id, p_action, 'burst', v_burst_start, 1, p_now),
    (p_user_id, p_action, 'daily', v_daily_start, 1, p_now)
  on conflict (user_id, action, bucket_type, bucket_start) do update
  set used_count = public.ai_quota_buckets.used_count + 1, updated_at = excluded.updated_at;

  return query select true, null::text, null::integer, null::timestamptz;
end;
$$;

create or replace function public.record_ai_rate_limit_event(
  p_user_id uuid, p_action text, p_event_type text
)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if p_action <> 'course_generate' or p_event_type not in ('lock_conflict', 'burst_rejected', 'daily_rejected') then
    raise invalid_parameter_value using message = 'invalid_ai_rate_limit_event';
  end if;
  insert into public.ai_rate_limit_events(user_id, action, event_type)
  values (p_user_id, p_action, p_event_type);
end;
$$;

revoke all on function public.acquire_ai_request_lock(uuid,text,text,timestamptz) from public, anon, authenticated;
revoke all on function public.release_ai_request_lock(uuid,text,text) from public, anon, authenticated;
revoke all on function public.consume_ai_quota(uuid,text,timestamptz) from public, anon, authenticated;
revoke all on function public.record_ai_rate_limit_event(uuid,text,text) from public, anon, authenticated;
grant execute on function public.acquire_ai_request_lock(uuid,text,text,timestamptz) to service_role;
grant execute on function public.release_ai_request_lock(uuid,text,text) to service_role;
grant execute on function public.consume_ai_quota(uuid,text,timestamptz) to service_role;
grant execute on function public.record_ai_rate_limit_event(uuid,text,text) to service_role;

commit;
