begin;

-- 고정 bucket은 경계에서 5분 이내 5회가 통과할 수 있다. 성공 시각을 보존해 정확한 rolling window를 센다.
create table if not exists public.ai_quota_consumptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action = 'course_generate'),
  consumed_at timestamptz not null default now()
);
create index if not exists ai_quota_consumptions_user_action_time_idx
  on public.ai_quota_consumptions(user_id, action, consumed_at);
alter table public.ai_quota_consumptions enable row level security;
revoke all on public.ai_quota_consumptions from public, anon, authenticated;

create or replace function public.consume_ai_quota(
  p_user_id uuid, p_action text, p_now timestamptz default now()
)
returns table (
  allowed boolean,
  limit_type text,
  retry_after_seconds integer,
  resets_at timestamptz
)
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_burst_limit constant integer := 3;
  v_daily_limit constant integer := 20;
  v_daily_start timestamptz := ((p_now at time zone 'Asia/Seoul')::date::timestamp at time zone 'Asia/Seoul');
  v_burst_count integer := 0;
  v_daily_count integer := 0;
  v_oldest_consumption timestamptz;
begin
  if p_action <> 'course_generate' then
    raise invalid_parameter_value using message = 'invalid_ai_action';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_action, 0));
  delete from public.ai_quota_consumptions
  where user_id = p_user_id and action = p_action
    and consumed_at <= p_now - interval '5 minutes';

  select count(*)::integer, min(consumed_at)
  into v_burst_count, v_oldest_consumption
  from public.ai_quota_consumptions
  where user_id = p_user_id and action = p_action;
  select used_count into v_daily_count from public.ai_quota_buckets
  where user_id = p_user_id and action = p_action and bucket_type = 'daily' and bucket_start = v_daily_start;
  v_daily_count := coalesce(v_daily_count, 0);

  if v_burst_count >= v_burst_limit then
    return query select false, 'burst', greatest(1, ceil(extract(epoch from ((v_oldest_consumption + interval '5 minutes') - p_now)))::integer), null::timestamptz;
    return;
  end if;
  if v_daily_count >= v_daily_limit then
    return query select false, 'daily', null::integer, v_daily_start + interval '1 day';
    return;
  end if;

  insert into public.ai_quota_consumptions(user_id, action, consumed_at)
  values (p_user_id, p_action, p_now);
  insert into public.ai_quota_buckets(user_id, action, bucket_type, bucket_start, used_count, updated_at)
  values (p_user_id, p_action, 'daily', v_daily_start, 1, p_now)
  on conflict (user_id, action, bucket_type, bucket_start) do update
  set used_count = public.ai_quota_buckets.used_count + 1, updated_at = excluded.updated_at;

  return query select true, null::text, null::integer, null::timestamptz;
end;
$$;

revoke all on function public.consume_ai_quota(uuid,text,timestamptz) from public, anon, authenticated;
grant execute on function public.consume_ai_quota(uuid,text,timestamptz) to service_role;

commit;
