import type {
  RecommendDateResponse,
  RecommendationRequest,
} from '../shared/recommendation/schemas';

export const recommendationRequestFixture: RecommendationRequest = {
  requestId: 'req-phase8-001',
  mode: 'course',
  language: 'ko',
  location: {
    source: 'kakao',
    kakaoPlaceId: 'origin-001',
    label: '서울숲',
    address: '서울 성동구',
    latitude: 37.544,
    longitude: 127.037,
    kind: 'landmark',
  },
  courseSteps: [
    { id: 'step-meal', category: 'meal', label: '식사' },
    { id: 'step-cafe', category: 'cafe', label: '카페' },
  ],
  maxWalkingMinutes: 10,
  totalBudgetKRW: 70_000,
  moods: ['quiet'],
  duration: 'half_day',
};

export const recommendDateResponseFixture: RecommendDateResponse = {
  requestId: recommendationRequestFixture.requestId,
  course: {
    requestId: recommendationRequestFixture.requestId,
    sessionId: recommendationRequestFixture.requestId,
    steps: [
      {
        stepId: 'step-meal',
        order: 1,
        category: 'meal',
        label: '식사',
        candidateId: 'candidate-meal',
        kakaoPlaceId: 'place-meal',
        name: '검증 식당',
        address: '서울 성동구',
        roadAddress: '서울 성동구 왕십리로 1',
        mapUrl: 'https://place.map.kakao.com/place-meal',
        latitude: 37.544,
        longitude: 127.037,
        reason: '검증된 식사 후보',
        locked: false,
      },
      {
        stepId: 'step-cafe',
        order: 2,
        category: 'cafe',
        label: '카페',
        candidateId: 'candidate-cafe',
        kakaoPlaceId: 'place-cafe',
        name: '검증 카페',
        address: '서울 성동구',
        roadAddress: '서울 성동구 왕십리로 2',
        mapUrl: 'https://place.map.kakao.com/place-cafe',
        latitude: 37.544,
        longitude: 127.037,
        reason: '검증된 카페 후보',
        locked: false,
      },
    ],
    relaxedConstraints: [],
    generatedAt: '2026-07-14T10:00:00.000Z',
  },
  cards: [{
    requestId: recommendationRequestFixture.requestId,
    sessionId: recommendationRequestFixture.requestId,
    title: '서울숲 데이트',
    summary: '식사와 카페를 이어 즐겨요.',
    estimated_time: '반나절',
    estimated_budget: '70,000원 이내',
    tags: ['course'],
    why_recommended: '선택한 코스 순서에 맞아요.',
    steps: [
      {
        label: '식사',
        candidateId: 'candidate-meal',
        kakaoPlaceId: 'place-meal',
        place_name: '검증 식당',
        place_address: '서울 성동구 왕십리로 1',
        map_url: 'https://place.map.kakao.com/place-meal',
      },
      {
        label: '카페',
        candidateId: 'candidate-cafe',
        kakaoPlaceId: 'place-cafe',
        place_name: '검증 카페',
        place_address: '서울 성동구 왕십리로 2',
        map_url: 'https://place.map.kakao.com/place-cafe',
      },
    ],
  }],
  metadata: {
    fallbackUsed: false,
    selectionSource: 'ai',
    selectionReason: 'none',
    search: {
      requestCount: 2,
      successfulCount: 2,
      failedCount: 0,
      rateLimitedCount: 0,
      timeoutCount: 0,
      candidateCount: 2,
    },
    route: {
      distanceMethod: 'haversine_straight_line',
      adjacentDistanceMeters: [0],
      totalDistanceMeters: 0,
      walkingHeuristicMetersPerMinute: 80,
      walkingLimitAssessment: 'provisional_within',
      hardConstraintValidated: false,
    },
  },
};

export function recommendationSessionRpcFixture() {
  const response = recommendDateResponseFixture;
  return {
    session: {
      id: response.course.sessionId,
      request_id: response.requestId,
      owner_user_id: '00000000-0000-4000-8000-000000000801',
      couple_id: 'couple-phase8',
      original_request: recommendationRequestFixture,
      current_course: response.course,
      cards: response.cards,
      metadata: response.metadata,
      status: 'draft',
      created_at: '2026-07-14T10:00:01.000Z',
      updated_at: '2026-07-14T10:00:01.000Z',
    },
    steps: response.course.steps.map((step) => ({
      session_id: response.course.sessionId,
      step_id: step.stepId,
      step_order: step.order,
      category: step.category,
      label: step.label,
      original_candidate_id: step.candidateId,
      original_kakao_place_id: step.kakaoPlaceId,
      current_candidate_id: step.candidateId,
      current_kakao_place_id: step.kakaoPlaceId,
      place_name: step.name,
      address: step.address,
      road_address: step.roadAddress,
      map_url: step.mapUrl,
      latitude: step.latitude,
      longitude: step.longitude,
      reason: step.reason,
      locked: step.locked,
      created_at: '2026-07-14T10:00:01.000Z',
      updated_at: '2026-07-14T10:00:01.000Z',
    })),
  };
}
